### ISSUE TITLE
[circle-ci][orb] "Install anchore tools" step fails

### ISSUE THREAD

**Issue by denismakogon** [anchore/ci-tools#10]
Seeing this issue during local image check that blocks the CI:
```
#!/bin/bash -eo pipefail
curl -o /tmp/anchore_ci_tools.py https://raw.githubusercontent.com/anchore/ci-tools/v0.3.2/scripts/anchore_ci_tools.py
chmod +x /tmp/anchore_ci_tools.py
pyenv global 3.6.5
pip install --upgrade pip
pip install --upgrade docker-compose
pip install --upgrade anchorecli
sed -i 's|/usr/bin/python3|/opt/circleci/.pyenv/shims/python3|' /tmp/anchore_ci_tools.py
ln -s /tmp/anchore_ci_tools.py /home/circleci/bin/anchore_ci_tools
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100 13404  100 13404    0     0  57973      0 --:--:-- --:--:-- --:--:-- 58025
Requirement already up-to-date: pip in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (19.0.3)
Requirement already up-to-date: docker-compose in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (1.24.0)
Requirement already satisfied, skipping upgrade: cached-property<2,>=1.2.0 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from docker-compose) (1.5.1)
Requirement already satisfied, skipping upgrade: websocket-client<1.0,>=0.32.0 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from docker-compose) (0.56.0)
Requirement already satisfied, skipping upgrade: PyYAML<4.3,>=3.10 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from docker-compose) (4.2b1)
Requirement already satisfied, skipping upgrade: six<2,>=1.3.0 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from docker-compose) (1.12.0)
Requirement already satisfied, skipping upgrade: docopt<0.7,>=0.6.1 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from docker-compose) (0.6.2)
Requirement already satisfied, skipping upgrade: requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from docker-compose) (2.20.0)
Requirement already satisfied, skipping upgrade: texttable<0.10,>=0.9.0 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from docker-compose) (0.9.1)
Requirement already satisfied, skipping upgrade: dockerpty<0.5,>=0.4.1 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from docker-compose) (0.4.1)
Requirement already satisfied, skipping upgrade: jsonschema<3,>=2.5.1 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from docker-compose) (2.6.0)
Requirement already satisfied, skipping upgrade: docker[ssh]<4.0,>=3.7.0 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from docker-compose) (3.7.2)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose) (2.7)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose) (2019.3.9)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose) (1.23)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from requests!=2.11.0,!=2.12.2,!=2.18.0,<2.21,>=2.6.1->docker-compose) (3.0.4)
Requirement already satisfied, skipping upgrade: docker-pycreds>=0.4.0 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from docker[ssh]<4.0,>=3.7.0->docker-compose) (0.4.0)
Requirement already satisfied, skipping upgrade: paramiko>=2.4.2; extra == "ssh" in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from docker[ssh]<4.0,>=3.7.0->docker-compose) (2.4.2)
Requirement already satisfied, skipping upgrade: pynacl>=1.0.1 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from paramiko>=2.4.2; extra == "ssh"->docker[ssh]<4.0,>=3.7.0->docker-compose) (1.3.0)
Requirement already satisfied, skipping upgrade: cryptography>=1.5 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from paramiko>=2.4.2; extra == "ssh"->docker[ssh]<4.0,>=3.7.0->docker-compose) (2.6.1)
Requirement already satisfied, skipping upgrade: bcrypt>=3.1.3 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from paramiko>=2.4.2; extra == "ssh"->docker[ssh]<4.0,>=3.7.0->docker-compose) (3.1.6)
Requirement already satisfied, skipping upgrade: pyasn1>=0.1.7 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from paramiko>=2.4.2; extra == "ssh"->docker[ssh]<4.0,>=3.7.0->docker-compose) (0.4.5)
Requirement already satisfied, skipping upgrade: cffi>=1.4.1 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from pynacl>=1.0.1->paramiko>=2.4.2; extra == "ssh"->docker[ssh]<4.0,>=3.7.0->docker-compose) (1.12.3)
Requirement already satisfied, skipping upgrade: asn1crypto>=0.21.0 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from cryptography>=1.5->paramiko>=2.4.2; extra == "ssh"->docker[ssh]<4.0,>=3.7.0->docker-compose) (0.24.0)
Requirement already satisfied, skipping upgrade: pycparser in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from cffi>=1.4.1->pynacl>=1.0.1->paramiko>=2.4.2; extra == "ssh"->docker[ssh]<4.0,>=3.7.0->docker-compose) (2.19)
Requirement already up-to-date: anchorecli in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (0.3.4)
Requirement already satisfied, skipping upgrade: click==7.0 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from anchorecli) (7.0)
Requirement already satisfied, skipping upgrade: prettytable==0.7.2 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from anchorecli) (0.7.2)
Requirement already satisfied, skipping upgrade: requests==2.20.0 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from anchorecli) (2.20.0)
Requirement already satisfied, skipping upgrade: urllib3==1.23 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from anchorecli) (1.23)
Requirement already satisfied, skipping upgrade: python-dateutil==2.7.3 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from anchorecli) (2.7.3)
Requirement already satisfied, skipping upgrade: PyYAML==4.2b1 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from anchorecli) (4.2b1)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from requests==2.20.0->anchorecli) (2019.3.9)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from requests==2.20.0->anchorecli) (2.7)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from requests==2.20.0->anchorecli) (3.0.4)
Requirement already satisfied, skipping upgrade: six>=1.5 in /opt/circleci/.pyenv/versions/3.6.5/lib/python3.6/site-packages (from python-dateutil==2.7.3->anchorecli) (1.12.0)
ln: failed to create symbolic link '/home/circleci/bin/anchore_ci_tools': File exists
Exited with code 1
```

build config:
```
  "python371_security_check":
    executor: anchore/anchore_engine
    working_directory: ~/fdk-python
    steps:
      - checkout
      - run:
          name: Python 3.7.1 build
          command: |
            ./build-images.sh 3.7.1
            mkdir -p /home/circleci/project/.circleci/.anchore/
            cp ~/fdk-python/.circleci/.anchore/policy_bundle.json /home/circleci/project/.circleci/.anchore/policy_bundle.json
      - anchore/analyze_local_image:
          image_name: fnproject/python:3.7.1-dev
          timeout: '500'
          policy_failure: true
      - anchore/analyze_local_image:
          image_name: fnproject/python:3.7.1
          timeout: '500'
          policy_failure: true
      - anchore/parse_reports

```

see build log for more details https://circleci.com/gh/fnproject/fdk-python/327

**Comment by denismakogon** [comment]
from build steps, the script that runs the following step is somehow buggy because if the following line:
```
ln -s /tmp/anchore_ci_tools.py /home/circleci/bin/anchore_ci_tools
```
there's must be a check of a symlink replacement command

**Comment by denismakogon** [comment]
This issue appears because of two sequential `anchore/analyze_local_image` checks.

Unfortunately, it's not documented anywhere that it's not allowed/possible/recommended to run this type of task.

**Comment by Btodhunter** [comment]
@denismakogon you are correct, this is definitely an issue with the current version of the orb. I will add a check to skip linking the tools script if it already exists.

Thanks for bringing this issue to my attention. I'll get a fix commited & published asap.

**Comment by denismakogon** [comment]
@Btodhunter thank you for your reply! So, just keep in mind that people might need to run multiple image checks (consider images for docker multistage builds) like the one I've posted above.

**Comment by denismakogon** [comment]
let me know when newer orb will be released

**Comment by denismakogon** [comment]
you know, it would be better to introduce a new structure to local image check task, for instance:
```yaml
  "python371_security_check":
    executor: anchore/anchore_engine
    working_directory: ~/fdk-python
    steps:
      - checkout
      - run:
          name: Python 3.7.1 build
          command: |
            ./build-images.sh 3.7.1
            mkdir -p /home/circleci/project/.circleci/.anchore/
            cp ~/fdk-python/.circleci/.anchore/policy_bundle.json /home/circleci/project/.circleci/.anchore/policy_bundle.json
      - anchore/analyze_local_image:
          - image_name: fnproject/python:3.7.1-dev
             timeout: '500'
             policy_failure: true
          - image_name: fnproject/python:3.7.1
             timeout: '500'
             policy_failure: true
      - anchore/parse_reports
```
this change wouldn't make you put a lot of checks into bash scripts, just make steps from `anchore/analyze_local_image` like `Install Anchore tools` run only once at the beginning.

the reason for such change is related to other steps as well because if you would need to check more than 1 image Circle will spend a lot of time spinning up the same infrastructure twice which will make builds run longer.

**Comment by denismakogon** [comment]
@Btodhunter any news so far?

**Comment by Btodhunter** [comment]
@denismakogon Yeah, I'm working on an update that will make this a non-issue. Hoping to get it published today.

As for your suggestion, I agree that would be a more ideal way of implementing the local scan job. However, CircleCI doesn't offer a list/array parameter type, so I don't know how to take in multiple parameters like that. The only way I can think of for allowing multiple images in a single job is by passing a BASH array as a string, like this: `'( "image_one" "image_two" "image_three" )'`. That solution wouldn't allow multiple options for "policy_failure", "timeout", or "policy_bundle_file_path" though.

**Comment by denismakogon** [comment]
okay, i see.

Let's make a short-term fix that i can use right away, because, you know, circle ci create the whole new stack of Achore for each check which is like a lot (see https://github.com/fnproject/fdk-node/pull/25).

Maybe, for the CI, there could be somewhat easier/faster to install as part of the orb (with no need to install a local registry, pulling and starting anchore engine, etc., but still use vuln db per-buit images.) and test an image within maybe a couple minutes, but less than 7-8.

**Comment by denismakogon** [comment]
```
  "python371_security_check":
    executor: anchore/anchore_engine
    working_directory: ~/fdk-python
    steps:
      - checkout
      - run:
          name: Python 3.7.1 build
          command: |
            ./build-images.sh 3.7.1
      - anchore/analyze_local_image:
          dev:
             image_name: fnproject/python:3.7.1-dev
             timeout: '500'
             policy_failure: true
          runtime:
             image_name: fnproject/python:3.7.1
             timeout: '500'
             policy_failure: true
      - anchore/parse_reports
```

would this syntax work?

**Comment by Btodhunter** [comment]
@denismakogon We definitely have plans to short circuit the engine and just run the analyzers directly for CI and our Inline Scanning script. I think that would make a good feature request, so we can get an idea of the demand for that kind of approach. 

For now, I'm working on getting the orb to utilize our inline_scan container, which already has a fully bootstrapped engine/db. This will remove the "start anchore-engine" step and shave ~2m from the orb scan. I'm still trying to think of a good solution for local scanning though, especially in regards to scanning multiple images. I'm running in to limitations with the CircleCI docker runner, as well as with the orb definition spec.

In regards to your latest syntax suggestion, unfortunately I don't think that the CircleCI orb definition allows nested parameters like that. I really think that the only way I can allow the specification of multiple images is with a stringified array. Which is a bit limiting due to the constraints I mentioned earlier.

**Comment by Btodhunter** [comment]
@denismakogon This issue is fixed in v1.3.0 of the orb, which was just published. The local image scan is now using our inline_scan script which can take in multiple images, however those images are limited to using the same policy bundle for evaluation. Multiple images can be scanned in a job like this: 
```
version: 2.1
orbs:
  anchore: anchore/anchore-engine@1.3.0
jobs:
  local_image_scan:
    executor: anchore/anchore_engine
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: build containers
          command: |
            docker build -t "example/test:dev" dev/
            docker build -t "example/test:staging" staging/
            docker build -t "example/test:latest" prod/
      - anchore/analyze_local_image:
          image_name: "example/test:dev example/test:staging example/test:latest"
          timeout: '500'
          policy_failure: True
          policy_bundle_file_path: .circleci/.anchore/policy_bundle.json
      - anchore/parse_reports
      - store_artifacts:
          path: anchore-reports
```

The image_name parameter can now take multiple images seperated with a space. This isn't an ideal implementation but I think that it will speed up your scanning times. Once circleci offers a list type for parameters, I will probably implement something like your suggestion.
