### ISSUE TITLE
Anchore orb cannot find custom policy_bundle.json file

### ISSUE THREAD

**Issue by paulros** [anchore/ci-tools#6]
**Summary:**
Anchore orb for circleci cannot find custom policy_bundle.json file.

**Steps to reproduse:**
Add a policy_bundle.json file to  [project_name]/.circleci/.anchore/
It's a default folder. The orb should find the file, but you can also add a parameter:
`policy_bundle_file_path: /home/circleci/project/.circleci/.anchore/policy_bundle.json`

**Expected results:** 
I used a defult policy_bundle.json file that I found [here](https://anchore.freshdesk.com/support/solutions/articles/36000074705-policy-bundles-and-evaluation)

**Actual results**
I've got this error:
```
#!/bin/bash -eo pipefail
(anchore-cli --json policy add "/home/circleci/project/.circleci/.anchore/policy_bundle.json" | jq '.policyId' | xargs anchore-cli policy activate) &> /dev/null || \
  printf "\n%s\n" "Custom policy bundle not found - /home/circleci/project/.circleci/.anchore/policy_bundle.json - using default policy bundle."
if true; then
  anchore-cli evaluate check "anchore-registry:5000/${CIRCLE_PROJECT_REPONAME}:ci" --detail
else
  (set +o pipefail; anchore-cli evaluate check "anchore-registry:5000/${CIRCLE_PROJECT_REPONAME}:ci" --detail | tee /dev/null)
fi

Custom policy bundle not found - /home/circleci/project/.circleci/.anchore/policy_bundle.json - using default policy bundle.
```

**Comments:**
My custom policy should pass all vulnerabilities expect critical, but the circleci job feils because the default policy is set to high. 

CircleCI pipeline code: 
```
version: 2.1
orbs:
  anchore: anchore/anchore-engine@1.2.1
jobs:
  local_image_scan:
    executor: anchore/anchore_engine
    steps:
      - checkout:
          path: ~/project/src/
      - run:
          name: build container
          command: docker build -t ${CIRCLE_PROJECT_REPONAME}:ci ~/project/src/
      - anchore/analyze_local_image:
          image_name: ${CIRCLE_PROJECT_REPONAME}:ci
          timeout: '500'
          policy_failure: True
          policy_bundle_file_path: /home/circleci/project/.circleci/.anchore/policy_bundle.json
      - anchore/parse_reports
workflows:
  scan_image:
    jobs:
      - local_image_scan:
          context: global
```

Path to policy_bundle.json
/home/user/project/.circleci/.anchore/policy_bundle.json
