### ISSUE TITLE
parse_reports uses incorrect json filenames

### ISSUE THREAD

**Issue by simoami** [anchore/ci-tools#8]
Based on the the supplied image name in the circleci config, the following files are generated according to the output:
```
...
Analysis completed!

Successfully generated anchore-reports/api-server_ci-content-os.json.
Successfully generated anchore-reports/api-server_ci-content-npm.json.
Successfully generated anchore-reports/api-server_ci-content-files.json.
Successfully generated anchore-reports/api-server_ci-vuln.json.
Successfully generated anchore-reports/api-server_ci-details.json.
Successfully generated anchore-reports/api-server_ci-policy.json.
```

However, the parse_reports step references these files:
```
anchore-reports/image-content-os-report.json
anchore-reports/image-vuln-report.json
```
Ref: https://github.com/anchore/ci-tools/blob/master/circleci-orbs/anchore-engine/orb.yml#L205-L207

So I get these errors instead:
```
The following OS packages are installed:
jq: error: Could not open file anchore-reports/image-content-os-report.json: No such file or directory

The following vulnerabilites were found:
jq: error: Could not open file anchore-reports/image-vuln-report.json: No such file or directory
```

My circleci config:
```
  local_image_scan:
    executor: anchore/anchore_engine
    steps:
      - checkout
      - run:
          name: Build image for scanning
          command: docker build -t ${CIRCLE_PROJECT_REPONAME}:ci .
      - anchore/analyze_local_image:
          image_name: ${CIRCLE_PROJECT_REPONAME}:ci
          timeout: '500'
          policy_failure: False
```
