### ISSUE TITLE
[feature] allow custom path for policy bundle

### ISSUE THREAD

**Issue by denismakogon** [anchore/ci-tools#9]
Follow-up on https://github.com/anchore/anchore-engine/issues/174

## intro

CircleCI Anchore orb allows using a bundle file that stored at `.circleci/.anchore/policy_bundle.json`.

However, there's a problem because `anchore/analyze_local_image` attempts to load custom bundle file from the following path:
```
/home/circleci/project/.circleci/.anchore/policy_bundle.json
```
when at most of the times it's not there and here's very simple circleci job template that breaks anchore orb:
```
  "python36_security_check":
    executor: anchore/anchore_engine
    working_directory: ~/go/src/github.com/fnproject/fdk-python
    steps:
      - checkout
      - run:
          name: Python 3.6 build
          command: |
            ./build-images.sh 3.6
      - anchore/analyze_local_image:
          image_name: fnproject/python:3.6-dev
          timeout: '500'
          policy_failure: true
      - anchore/analyze_local_image:
          image_name: fnproject/python:3.6
          timeout: '500'
          policy_failure: true
      - anchore/parse_reports
```

as you may notice, there's `working_directory: ~/go/src/github.com/fnproject/fdk-python` that changes working directory and make impossible to find bundle file for anchore:
```bash
#!/bin/bash -eo pipefail
(anchore-cli --json policy add /home/circleci/project/.circleci/.anchore/policy_bundle.json | jq '.policyId' | xargs anchore-cli policy activate) &> /dev/null || \
  printf "\n%s\n" "Custom policy bundle not found - /home/circleci/project/.circleci/.anchore/policy_bundle.json - using default policy bundle."
if true; then
  anchore-cli evaluate check anchore-registry:5000/fnproject/python:3.6-dev --detail
else
  (set +o pipefail; anchore-cli evaluate check anchore-registry:5000/fnproject/python:3.6-dev --detail | tee /dev/null)
fi

Custom policy bundle not found - /home/circleci/project/.circleci/.anchore/policy_bundle.json - using default policy bundle.

```

**Comment by denismakogon** [comment]
That's quite unfortunate, I made some changes to my job template:
```yaml
  "python371_security_check":
    executor: anchore/anchore_engine
    working_directory: ~/fdk-python
    steps:
      - checkout
      - run:
          name: Python 3.7.1 build
          command: |
            ./build-images.sh 3.7.1
            mkdir -p /home/circleci/project/.circleci/.anchore/
            cp ~/fdk-python/.circleci/.anchore/policy_bundle.json /home/circleci/project/.circleci/.anchore/policy_bundle.json
            cat /home/circleci/project/.circleci/.anchore/policy_bundle.json
      - anchore/analyze_local_image:
          image_name: fnproject/python:3.7.1-dev
          timeout: '500'
          policy_failure: true
      - anchore/analyze_local_image:
          image_name: fnproject/python:3.7.1
          timeout: '500'
          policy_failure: true
      - anchore/parse_reports

```

as you can see, i copied custom bundle file to `/home/circleci/project/.circleci/.anchore/policy_bundle.json`

at the end of the image build i see the following:
```json
# policies available here: https://anchore.freshdesk.com/support/solutions/articles/36000073896-anchore-policy-checks
{
  "name": "IgnoreUnfixablePkgs",
  "version": "1_0",
  "comment": "Policy for basic checks",
  "id": "ba6daa06-da3b-46d3-9e22-f01f07b0489a",
  "rules": [
    {
      "action": "STOP",
      "gate": "vulnerabilities",
      "id": "80569900-d6b3-4391-b2a0-bf34cf6d813d",
      "params": [
        { "name": "package_type", "value": "all" },
        { "name": "severity_comparison", "value": ">=" },
        { "name": "severity", "value": "medium" },
        { "name": "fix_available", "value": "true"}
      ],
      "trigger": "package"
    }
  ]
}
```

it means that the custom bundle file exists in two locations: `~/fdk-python/.circleci/.anchore/policy_bundle.json` and `/home/circleci/project/.circleci/.anchore/policy_bundle.json`. So, I had an assumption that it must work, but it's not:
```
#!/bin/bash -eo pipefail
(anchore-cli --json policy add /home/circleci/project/.circleci/.anchore/policy_bundle.json | jq '.policyId' | xargs anchore-cli policy activate) &> /dev/null || \
  printf "\n%s\n" "Custom policy bundle not found - /home/circleci/project/.circleci/.anchore/policy_bundle.json - using default policy bundle."
if true; then
  anchore-cli evaluate check anchore-registry:5000/fnproject/python:3.7.1-dev --detail
else
  (set +o pipefail; anchore-cli evaluate check anchore-registry:5000/fnproject/python:3.7.1-dev --detail | tee /dev/null)
fi

Custom policy bundle not found - /home/circleci/project/.circleci/.anchore/policy_bundle.json - using default policy bundle.

```

Still the same.

What am I missing?
